name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  PROJECT_ID: tokenner-dev
  GAR_LOCATION: us-central1
  REPOSITORY: mw-service-dev
  SERVICE: sample-service
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.NON_PROD_GCP_SA }}'

      - name: Set Commit SHA for Tagging
        id: set_image_tag
        run: |
          echo "image_tag=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "::set-output name=image_tag::${GITHUB_SHA}"

      - name: Build and Push Container
        run: |
          gcloud builds submit --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ steps.set_image_tag.outputs.image_tag }} .

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.NON_PROD_GCP_SA }}'

      - name: Ensure IMAGE_TAG is Properly Set
        run: |
          # Verify that IMAGE_TAG is set
          if [ -z "${IMAGE_TAG}" ]; then
            echo "No IMAGE_TAG set. Exiting..."
            exit 1
          fi
          echo "Deploying image: $IMAGE_TAG"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ env.IMAGE_TAG }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
